---
  # No trailing slash!
  base_url: http://flyingchicken.herokuapp.com
  github:
    account: codeforamerica
    type: org
    # define this here or with 'heroku config:add GITHUB_ACCESS_TOKEN=....'
    access_token: 