---
  base_url: http://flyingchicken.herokuapp.com # No trailing slash!
  github:
    account: codeforamerica
    type: org
    access_token:  # define this here or with 'heroku config:add GITHUB_ACCESS_TOKEN=....'