---
  # No trailing slash!
  base_url: http://flyingchicken.herokuapp.com
  github:
    account: codeforamerica
    type: org
    # define this here or with 'heroku config:add GITHUB_ACCESS_TOKEN=....'
    access_token: 
  # Eggs are pushes that chicken should make to other services.  
  # Associative array, key is arbitrary
  eggs:
    commitalization: http://commits.codeforamerica.org/committed
    office_chicken: http://173.228.102.131:6178/receive_commit
    synstats: http://synstats.herokuapp.com/posthook
    egg-hatcher: http://egg-hatcher.nodester.com/
